f2fs: convert f2fs_msg to new f2fs_info macros
* Needed after f2fs: introduce f2fs_<level> macros to wrap f2fs_printk()
* Solves:

../fs/f2fs/gc.c:36:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO, "Catching wakelock for GC");
                        ^
../fs/f2fs/gc.c:36:4: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
../fs/f2fs/gc.c:41:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO, "Unlocking wakelock for GC");
                        ^
../fs/f2fs/gc.c:146:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO,
                        ^
../fs/f2fs/gc.c:247:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO,
                        ^

Signed-off-by: David Trpchevski <trpcevski.david@gmail.com>

# Conflicts:
#	fs/f2fs/gc.c